apiVersion: v1
kind: Secret
metadata:
  name: kryptic-journal-secrets
  namespace: kryptic-journal
type: Opaque
data:
  # Base64 encoded values - replace with your actual values:
  # echo -n "your-password" | base64
  POSTGRES_PASSWORD: a3J5cHRpY19wYXNzd29yZA== # kryptic_password
  JWT_SECRET: eW91ci1zdXBlci1zZWN1cmUtand0LXNlY3JldC1rZXktZm9yLXByb2R1Y3Rpb24= # your-super-secure-jwt-secret-key-for-production
  ENCRYPTION_KEY: YTFiMmMzZDRlNWY2Nzg5MDEyMzQ1Njc4OTAxMjM0NTY3ODkwYWJjZGVmMTIzNDU2Nzg5MGFiY2RlZjEyMzQ1Ng== # a1b2c3d4e5f6789012345678901234567890abcdef1234567890abcdef123456 